replicaCount: 1
imagePullPolicy: Always
logLevel: debug
chatHistorySize: 50
service:
  type: ClusterIP
  port: 3000
database:
  url: "dbi:Pg:dbname=wordwonk;host=postgresql"
  user: "wordwonk_backend"
