apiVersion: v1
kind: ConfigMap
metadata:
  name: wordwonk-locales
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: wordwonk
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}
data:
  en.json: |-
{{ .Files.Get "share/locale/en.json" | nindent 4 }}
  es.json: |-
{{ .Files.Get "share/locale/es.json" | nindent 4 }}
  fr.json: |-
{{ .Files.Get "share/locale/fr.json" | nindent 4 }}
  de.json: |-
{{ .Files.Get "share/locale/de.json" | nindent 4 }}
  ru.json: |-
{{ .Files.Get "share/locale/ru.json" | nindent 4 }}


