{{- if .Values.global.persistence.manualPV -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordwonk-db-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.primary.persistence.size | default "10Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass | default "wordwonk-db-local" }}
  hostPath:
    path: /mnt/k8s-volumes/wordwonk-db
    type: DirectoryOrCreate
{{- end -}}

