apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.global.namespace | default "Wordwonk" }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
  backend-db-user: {{ .Values.backend.database.user | quote }}
  backend-db-pass: {{ .Values.postgresql.auth.password | quote }}
  google-client-id: {{ .Values.auth.google.clientId | quote }}
  google-client-secret: {{ .Values.auth.google.clientSecret | quote }}
  discord-client-id: {{ .Values.auth.discord.clientId | quote }}
  discord-client-secret: {{ .Values.auth.discord.clientSecret | quote }}
  admin-discord-webhook: {{ .Values.auth.notifications.discordWebhook | quote }}
