apiVersion: v2
name: wordwonk
description: Umbrella chart for the wordwonk polyglot microservices stack
type: application
version: 0.18.0
appVersion: "1.14.0"

dependencies:
  - name: frontend
    version: 0.11.0
    repository: "file://../srv/frontend/helm"
    condition: frontend.enabled
  - name: wordd
    version: 0.11.0
    repository: "file://../srv/wordd/helm"
    condition: wordd.enabled
  - name: backend
    version: 0.11.0
    repository: "file://../srv/backend/helm"
    condition: backend.enabled
  - name: postgresql
    version: 15.5.21
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

maintainers:
  - name: Ron "Quinn" Straight
    email: straightre@gmail.com
    url: https://fazigu.org
